apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    eliona.io/brokers: "true"
    eliona.io/database: "true"
    eliona.io/pgp-keys: "true"
  labels:
    app: forecast
  name: forecast
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  selector:
    matchLabels:
      app: forecast
  serviceName: forecast
  template:
    metadata:
      labels:
        app: forecast
    spec:
      containers:
        - image: eliona/forecast-app:develop
          imagePullPolicy: Always
          name: forecast
          resources:
            limits:
              cpu: "1"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /tmp
              name: datadir
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: Always
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: datadir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
